<script src="outside/assets/js/jquery.min.js"></script>
<script src="outside/assets/js/jquery-migrate-3.0.1.min.js"></script>
<script src="outside/assets/js/popper.min.js"></script>
<script src="outside/assets/js/bootstrap.min.js"></script>
<script src="outside/assets/js/jquery.easing.1.3.js"></script>
<script src="outside/assets/js/jquery.waypoints.min.js"></script>
<script src="outside/assets/js/jquery.stellar.min.js"></script>
<script src="outside/assets/js/owl.carousel.min.js"></script>
<script src="outside/assets/js/jquery.magnific-popup.min.js"></script>
<script src="outside/assets/js/aos.js"></script>
<script src="outside/assets/js/jquery.animateNumber.min.js"></script>
<script src="outside/assets/js/bootstrap-datepicker.js"></script>
<script src="outside/assets/js/jquery.timepicker.min.js"></script>
<script src="outside/assets/js/scrollax.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="outside/assets/js/google-map.js"></script>
<script src="outside/assets/js/price_rangs.js"></script>
<script src="outside/assets/js/main.js"></script>